version: '2'

networks:
  default:

services:
  dittovc:
    build: .
    restart: unless-stopped
    networks:
      - default

volumes:
  - /your/local/path/to/config.json:/home/node/app/config.json
  - /your/local/path/to/firebase.json:/home/node/app/firebase.json