version: '3'

services:
  dittovc:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    networks:
      - dittovc-bot-network
    volumes:
      - ./config.json:/home/node/app/config.json:ro
      - ./firebase.json:/home/node/app/firebase.json:ro

networks:
  dittovc-bot-network: