# This is a basic workflow to help you get started with Actions

name: Continuous Delivery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Build and deploy the application
        run: |
          pm2 stop dittovc
          cp -r $GITHUB_WORKSPACE/* /home/sha_tindle/repos/DittoVC
          rm -rf /home/sha_tindle/repos/DittoVC/node_modules
          cd /home/sha_tindle/repose/DittoVC
          npm install
          npm audit fix || true
          pm2 restart dittovc
